services:
  windows:
    container_name: windows
    image: ghcr.io/dockur/windows
    environment:
      RAM_SIZE: "16GB"
      DISK_SIZE: "10TB"
      CPU_CORES: "32"
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/kfd          # AMD compute device
      - /dev/dri          # AMD graphics device (render nodes)
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: on-failure
    stop_grace_period: 2m
